version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    labels:
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.${APPDOMAIN:-local}`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=mikkorauhala:$$apr1$$8o0nzfxa$i5M5eq8FhDsxVdFExiUJN0"
    volumes:
      - prometheus-storage:/prometheus
      - prometheus-config:/etc/prometheus
    networks:
      - traefik-network
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_DOMAIN=grafana.${APPDOMAIN:-local}
      - GF_SERVER_ROOT_URL=https://%(domain)s/
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.${APPDOMAIN:-local}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - traefik-network
      
volumes:
  prometheus-storage:
  prometheus-config:
  grafana-storage:

networks:
    traefik-network:
      external: true
      
